
export default {
  REACT_APP_API_URL: process.env.REACT_APP_API_URL,
  MAIN_MENU_ITEMS: ['REGISTER', 'SUPPORT'],
  ADMIN_MENU_ITEMS: ['ADMIN BOARD', 'FUNCTIONS','SUPPORT'],
  MEMBER_MENU_ITEMS: ['PROFILE', 'ANALYTICS', 'SERVICES', 'HELP']
}
