export default {
  MAIN_MENU_ITEMS: ['ONBOARDING', 'SUPPORT'],
  SYSTEM_ADMIN_MENU_ITEMS: ['ADMIN'],
  ADMIN_MENU_ITEMS: ['USER MANAGEMENT'],
  CSR_MENU_ITEMS: ['USER MANAGEMENT'],
  FIELD_AGENT_MENU_ITEMS: ['USER MANAGEMENT'],
  MEMBER_MENU_ITEMS: ['FARM RECORDS','ANALYTICS', 'SERVICES', 'HELP'],
}
