export default {
  ROOT: '/',
  ADMIN: '/admin',
  PROFILE: '/profile',
  LOGIN: '/',
  SIGNUP: '/signup',
  SUPPORT: '/support',
  FUNCTIONS: '/functions',
  HELP: '/help',
  FARMRECORDS: '/farmrecords',
  CROPRECORDS: '/croprecords',
  ANALYTICS: '/analytics',
  LOGOUT: '/logout',
  USERMANAGEMENT: '/usermanagement',
  SERVICES: '/services',
  RESET: '/reset',
};
