export default {
  ROOT: '/',
  ADMIN: '/admin',
  PROFILE: '/profile',
  LOGIN: '/login',
  STAFF: '/staff',
  SIGNUP: '/signup',
  SUPPORT: '/support',
  FUNCTIONS: '/functions',
  HELP: '/help',
  FARMRECORDS: '/farmrecords',
  CROPRECORDS: '/croprecords',
  TASKS: '/tasks',
  WAREHOUSE: '/warehouse',
  ANALYTICS: '/analytics',
  LOGOUT: '/logout',
  USERMANAGEMENT: '/usermanagement',
  SERVICES: '/services',
  RESET: '/reset',
  CHC: '/chc',
  SME: '/sme',
  NOTIFICATIONS: '/notifications',
};
